[project]
name = "cuda-cpp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "ipython>=9.13.0",
    "jupyter-dark-detect>=0.1.0",
    "jupyterlab>=4.5.7",
    "jupyterlab-nvidia-nsight>=1.0.0",
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "pip>=26.1.1",
]
